### ISSUE TITLE
大佬有计划升级4.1的sdk吗

### ISSUE THREAD

**Issue by langmansh** [DavidSciMeow/Meow.FaceRecon#17]
大佬有计划升级4.1的sdk吗

**Comment by RoslynMeow** [comment]
可以写，应该改动不是特别大

**Comment by RoslynMeow** [comment]
> 大佬有计划升级4.1的sdk吗

你需要我就写

**Comment by RoslynMeow** [comment]
![image](https://user-images.githubusercontent.com/31565570/170838028-37d62118-2153-45b5-9fc1-8c779eec544f.png)
目前第四版的已经差不多能用了,你大概需要多少功能?

**Comment by DavidSciMeow** [comment]
有任何问题还是在这里追吧(233
我给他开放了
